# Generated by Django 4.2.26 on 2025-11-09 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Option 1'), ('B', 'Option 2'), ('C', 'Option 3'), ('D', 'Option 4')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Option 1', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Option 2', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Option 3', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Option 4', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
