# Generated by Django 4.2.26 on 2025-11-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quizattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
